export const CONFIGURATION_SETTINGS_SUCCESS = "CONFIGURATION_SETTINGS_SUCCESS";
export const SELECTED_SETTING_SUCCESS = "SELECTED_SETTING_SUCCESS";
export const REQUEST_WAITING = "REQUEST_WAITING";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const SET_LAST_MESSAGE = "SET_LAST_MESSAGE";
